### ISSUE TITLE
[Server] comment - 댓글 삭제

### ISSUE THREAD

**Issue by james-taeil** [codestates/Code-High#101]
### ISSUE
- Group: `server`
- Type:  `feature`
- Detail:  로그인 유저가 선택한 댓글 삭제 기능 구현

### TODO
1. [ ] DELETE 요청 시, 작동되는 로직 구현
2. [ ] 관리자, 사용자 권한 둘 다 주기
3. [ ] DB에 댓글 삭제 후 저장

### Labels
- Estimated time: `E: 3h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `High`
