### ISSUE TITLE
[Server] 배포 - 도메인 연결 및 https로 test server 배포

### ISSUE THREAD

**Issue by loverduck** [codestates/Code-High#27]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 도메인 연결 및 https로 test server 배포

### TODO
1. [x] 도메인 연결 설정 - api.codehigh.club
2. [x] route53 및 ELB를 사용한 https 서버 배포
3. [x] get 요청 테스트

### Labels
- Estimated time: `E: 3h`
- Group: `server`
- Sprint: `Sprint1`
- Urgency: `High`
