### ISSUE TITLE
[Server] 회원가입 - 이메일 회원가입 시, 인증 이메일 전송

### ISSUE THREAD

**Issue by james-taeil** [codestates/Code-High#3]
### ISSUE
- Group: `server`
- Type:  `feature`
- Detail: 이메일 회원 가입 시 해당 이메일로 인증 메일 가는지 확인

### TODO
1. [x] POST 요청으로 DB에 저장
2. [x] 토큰 메일로 보내주기
3. [ ] kakao, google, github 으로 회원가입 시 해당 유저 정보 받아오기
4. [x] 받아온 정보 DB에 저장

### Labels
- Estimated time: `E: 3h`
- Group: `server`
- Sprint: `Sprint2`
- Urgency: `High`
