### ISSUE TITLE
[Server] comment - 댓글 목록

### ISSUE THREAD

**Issue by james-taeil** [codestates/Code-High#77]
### ISSUE
- Group: `server`
- Type:  `feature`
- Detail:  댓글 목록 보여주는 로직 구현 하기

### TODO
1. [ ] GET 요청 시, 작동되는 로직 구현
2. [ ] DB에 요청한 원하는 데이터 값 가져오기
3. [ ] 관리자, 사용자 권한 둘 다 주기

### Labels
- Estimated time: `E: 3h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `High`
