### ISSUE TITLE
[Server] comment - 댓글 달기

### ISSUE THREAD

**Issue by james-taeil** [codestates/Code-High#90]
### ISSUE
- Group: `server`
- Type:  `feature`
- Detail:  댓글 달기 요청 시, 댓글 달리기, 데이터 저장

### TODO
1. [ ] POST 요청 시, 작동되는 로직 구현
2. [ ] 사용자만 권한 둘 다 주기
3. [ ] DB에 데이터 저장

### Labels
- Estimated time: `E: 3h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `High`
